export interface FocusNfeCompanyResponse {
    id: number
    nome: string
    nome_fantasia: string
    inscricao_estadual: string
    inscricao_municipal: null
    bairro: string
    cargo_responsavel: null
    cep: null
    cnpj: null
    cpf: string
    codigo_municipio: string
    codigo_pais: string
    codigo_uf: string
    complemento: string
    cpf_cnpj_contabilidade: null
    cpf_responsavel: string
    discrimina_impostos: boolean
    email: string
    enviar_email_destinatario: boolean
    enviar_email_homologacao: boolean
    habilita_nfce: boolean
    habilita_nfe: boolean
    habilita_nfse: boolean
    habilita_nfsen_producao: null
    habilita_nfsen_homologacao: null
    habilita_cte: boolean
    habilita_mdfe: boolean
    habilita_manifestacao: boolean
    habilita_manifestacao_homologacao: boolean
    habilita_manifestacao_cte: boolean
    habilita_manifestacao_cte_homologacao: boolean
    logradouro: string
    municipio: string
    nome_responsavel: string
    numero: string
    pais: string
    regime_tributario: string
    telefone: string
    uf: string
    habilita_contingencia_offline_nfce: boolean
    habilita_contingencia_epec_nfce: boolean
    reaproveita_numero_nfce_contingencia: boolean
    mostrar_danfse_badge: boolean
    csc_nfce_producao: null
    id_token_nfce_producao: null
    csc_nfce_homologacao: null
    id_token_nfce_homologacao: null
    proximo_numero_nfe_producao: number
    proximo_numero_nfe_homologacao: number
    serie_nfe_producao: string
    serie_nfe_homologacao: string
    proximo_numero_nfse_producao: null
    proximo_numero_nfse_homologacao: null
    proximo_numero_nfsen_producao: null
    proximo_numero_nfsen_homologacao: null
    serie_nfse_producao: null
    serie_nfse_homologacao: null
    serie_nfsen_producao: null
    serie_nfsen_homologacao: null
    proximo_numero_nfce_producao: number
    proximo_numero_nfce_homologacao: number
    serie_nfce_producao: string
    serie_nfce_homologacao: string
    proximo_numero_cte_producao: null
    proximo_numero_cte_homologacao: null
    serie_cte_producao: null
    serie_cte_homologacao: null
    proximo_numero_cte_os_producao: null
    proximo_numero_cte_os_homologacao: null
    serie_cte_os_producao: null
    serie_cte_os_homologacao: null
    proximo_numero_mdfe_producao: null
    proximo_numero_mdfe_homologacao: null
    serie_mdfe_producao: null
    serie_mdfe_homologacao: null
    certificado_valido_ate: string
    certificado_valido_de: string
    certificado_cnpj: null
    certificado_especifico: boolean
    data_ultima_emissao: null
    caminho_logo: null
    login_responsavel: null
    senha_responsavel_preenchida: boolean
    orientacao_danfe: null
    recibo_danfe: boolean
    exibe_sempre_ipi_danfe: boolean
    exibe_issqn_danfe: boolean
    exibe_impostos_adicionais_danfe: boolean
    exibe_fatura_danfe: boolean
    exibe_unidade_tributaria_danfe: boolean
    exibe_desconto_itens: boolean
    exibe_sempre_volumes_danfe: boolean
    exibe_composicao_carga_mdfe: boolean
    data_inicio_recebimento_nfe: null
    data_inicio_recebimento_cte: null
    habilita_csrt_nfe: boolean
    nfe_sincrono: boolean
    nfe_sincrono_homologacao: boolean
    mdfe_sincrono: null
    mdfe_sincrono_homologacao: null
    smtp_endereco: null
    smtp_dominio: null
    smtp_autenticacao: null
    smtp_porta: null
    smtp_login: null
    smtp_remetente: null
    smtp_responder_para: null
    smtp_modo_verificacao_openssl: null
    smtp_habilita_starttlls: boolean
    smtp_ssl: boolean
    smtp_tls: boolean
    token_producao: string
    token_homologacao: string
    client_app_id: number
}
