name: CD - DEV

on:
    push:
        branches:
            - dev_online

jobs:
    build-and-deploy:
        name: Build and Deploy
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Code
              uses: actions/checkout@v3

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v2

            - name: Set up Docker
              run: |
                  curl -fsSL https://get.docker.com -o get-docker.sh
                  sudo sh get-docker.sh

            - name: Log in to Docker Hub
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Extract Version from package.json
              id: version
              run: |
                  VERSION=$(jq -r '.version' package.json)
                  echo "VERSION=$VERSION" >> $GITHUB_ENV

            - name: Replace API URL in backend.ts
              run: sed -i 's|s://api.startja.boz.app.br|s://api.dev.startja.boz.app.br|' src/backend/backend.ts

            - name: Build and Push Docker Image
              run: |
                  docker compose -f docker-compose.dev.yml build --no-cache
                  docker compose -f docker-compose.dev.yml push

            - name: Deploy to Server via SSH
              uses: appleboy/ssh-action@v0.1.6
              with:
                  host: boz.app.br
                  username: root
                  port: 22
                  key: ${{ secrets.SSH_PRIVATE_KEY }}
                  known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }} # Remove this line if you disable host key checking
                  script: |
                      cd /home/startja/startja2.native
                      git pull
                      docker compose -f docker-compose.dev.yml pull
                      docker compose -f docker-compose.dev.yml up -d
